apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: spring-controller
spec:
  replicas: 1
  selector:
    app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: akashkadao/spring-boot-mongo
        name: springboot
        ports:
        - name: springboot
          containerPort: 8080  
       
---
apiVersion: apps/v1
kind: Service
metadata:
  lables:
    name: springboot
  name: springboot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot
---
# Mongo RC with host path Volume
apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: mongo-controller
spec:
  replicas: 1
  selector:
    app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - containerPort: 27017
          hostPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongo-persistent-storage
        hostPath:
         path: /tmp/dbbackup
---
# Mongo Node Port RC
apiVersion: apps/v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongo
