--- 
apiVersion: apps/v1
kind: ReplicationController
metadata: 
  name: spring-controller
spec: 
  replicas: 1
  selector: 
    app: springboot
  template: 
    metadata: 
      labels: 
        app: springboot
    spec: 
      containers: 
        - 
          image: akashkadao/spring-boot-mongo
          name: springboot
          ports: 
            - 
              containerPort: 8080
              name: springboot

       
--- 
apiVersion: apps/v1
kind: Service
metadata: 
  lables: 
    name: springboot
  name: springboot
spec: 
  ports: 
    - 
      port: 8080
      targetPort: 8080
  selector: 
    app: springboot
  type: NodePort

--- 
apiVersion: apps/v1
kind: ReplicationController
metadata: 
  name: mongo-controller
spec: 
  replicas: 1
  selector: 
    app: mongo
  template: 
    metadata: 
      labels: 
        app: mongo
    spec: 
      containers: 
        - 
          image: mongo
          name: mongo
          ports: 
            - 
              containerPort: 27017
              hostPort: 27017
          volumeMounts: 
            - 
              mountPath: /data/db
              name: mongo-persistent-storage
      volumes: 
        - 
          hostPath: 
            path: /tmp/dbbackup
          name: mongo-persistent-storage

--- 
apiVersion: apps/v1
kind: Service
metadata: 
  name: mongo
spec: 
  ports: 
    - 
      port: 27017
      targetPort: 27017
  selector: 
    app: mongo
  type: ClusterIP
